-- Create table for storing user badges
create table if not exists public.user_badges (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete cascade not null,
    badge_id text not null,
    awarded_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique (user_id, badge_id)
);

-- Enable RLS
alter table public.user_badges enable row level security;

-- Policies
create policy "Users can view their own badges"
on public.user_badges for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own badges (via game logic)"
on public.user_badges for insert
to authenticated
with check (auth.uid() = user_id);
